// ios_glue.c — everything the engine links against that unix_main.c and
// the SDL backends provided on desktop. Compiled against engine headers;
// the ObjC/Metal side lives in ios_metal.m behind plain C calls.

#include <unistd.h>

#include "client/client.h"
#include "server/server.h"          // svs.time — authoritative sim clock (sim-rate)
#include "renderercommon/tr_public.h"

// ---- ios_metal.m ----
int   Q3E_LayerWidth(void);
int   Q3E_LayerHeight(void);
int   Q3E_DisplayMaxFPS(void);
void *Q3E_GetInstanceProcAddr(void *instance, const char *name);
int   Q3E_CreateMetalSurface(void *instance, void **surfaceOut);

static char q3e_docs[1024];

void Q3E_SetDocumentsPath(const char *path) {
	Q_strncpyz(q3e_docs, path, sizeof(q3e_docs));
}

// ---- remote console bridge (ios_console.m) ----
void Q3E_ConsoleBridge_Start(void);
void Q3E_ConsoleBridge_Drain(void);
void Q3E_ConsoleBridge_Output(const char *text);
static qboolean q3e_bridge_active = qfalse;

void q3e_console_command(const char *text) {
	Cbuf_AddText(text);
	Cbuf_AddText("\n");
}

// ---- input shims (called from ios_input.m) ----

void Q3E_Input_Frame(void); // ios_input.m

void Q3E_QueueMouse(int dx, int dy) {
	Sys_QueEvent(0, SE_MOUSE, dx, dy, 0, NULL);
}

void Q3E_QueueJoyAxis(int axis, int value) {
	Sys_QueEvent(0, SE_JOYSTICK_AXIS, axis, value, 0, NULL);
}

void Q3E_QueueNamedKey(const char *name, int down) {
	const int key = Key_StringToKeynum(name);
	if (key > 0) {
		Sys_QueEvent(0, SE_KEY, key, down ? 1 : 0, 0, NULL);
	}
}

void Q3E_QueueChar(int ch) {
	Sys_QueEvent(0, SE_CHAR, ch, 0, 0, NULL);
}

// Run a console command from the input layer (main/engine thread) — for
// controller binds that map to a command rather than a key (e.g. centerview).
void Q3E_QueueCommand(const char *cmd) {
	Cbuf_AddText(cmd);
	Cbuf_AddText("\n");
}

// Active mod dir ("" = baseq3) — the touch layer picks the UI-cursor
// transform per game (mod UIs handle widescreen differently).
const char *Q3E_CurrentGame(void) {
	return Cvar_VariableString("fs_game");
}

// Menu mode: taps should click a UI cursor rather than drive gameplay.
int Q3E_MenuMode(void) {
	if (Key_GetCatcher() & (KEYCATCH_UI | KEYCATCH_CONSOLE)) {
		return 1;
	}
	return cls.state != CA_ACTIVE;
}

// ---- boot + frame (called from AppShell.m) ----

extern const char *q3e_ios_stamp; // generated by build-spike.sh

static qboolean q3e_booted = qfalse;

// ---- Shortcuts / URL-scheme mod launching ----
// One pending slot: set before boot -> baked into the boot command
// line; set after boot -> immediate hot-switch via game_restart.

static char q3e_pending_mod[64];

static int q3e_mod_exists(const char *mod) {
	char path[1200];
	if (!mod[0] || !strcmp(mod, "baseq3")) {
		return 1;
	}
	Com_sprintf(path, sizeof(path), "%s/%s", q3e_docs, mod);
	return access(path, F_OK) == 0;
}

void Q3E_RequestMod(const char *mod) {
	char clean[64];
	int i, j = 0;

	// sanitize: fs_game-legal chars only (it becomes a filesystem path)
	for (i = 0; mod && mod[i] && j < 63; i++) {
		char c = mod[i];
		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		    (c >= '0' && c <= '9') || c == '_' || c == '-') {
			clean[j++] = c;
		}
	}
	clean[j] = '\0';

	if (!q3e_mod_exists(clean)) {
		fprintf(stderr, "Q3E shortcuts: mod dir '%s' not found — ignoring\n", clean);
		return;
	}

	if (!q3e_booted) {
		Q_strncpyz(q3e_pending_mod, clean, sizeof(q3e_pending_mod));
		fprintf(stderr, "Q3E shortcuts: boot mod set to '%s'\n", clean);
		return;
	}

	// hot switch (main thread: URL opens and intent perform both are)
	char cmd[128];
	if (!clean[0] || !strcmp(clean, "baseq3")) {
		Com_sprintf(cmd, sizeof(cmd), "game_restart \"\"\n");
	} else {
		Com_sprintf(cmd, sizeof(cmd), "game_restart %s\n", clean);
	}
	fprintf(stderr, "Q3E shortcuts: hot-switching -> %s", cmd);
	Cbuf_AddText(cmd);
}

// One-time config migrations for EXISTING installs. Fresh installs bake the
// modern defaults into their first config (below); an install that already
// has a config predates those defaults, so we override the stale value
// exactly once — a marker file gates it so we never fight a choice the user
// later makes. Bump the level when adding a new one-time default.
#define Q3E_MIGRATION_LEVEL 2

static int q3e_migration_level(void) {
	char p[1200];
	Com_sprintf(p, sizeof(p), "%s/.q3e_migrations", q3e_docs);
	FILE *f = fopen(p, "rb");
	int lvl = 0;
	if (f) {
		if (fscanf(f, "%d", &lvl) != 1) lvl = 0;
		fclose(f);
	}
	return lvl;
}

static void q3e_set_migration_level(int lvl) {
	char p[1200];
	Com_sprintf(p, sizeof(p), "%s/.q3e_migrations", q3e_docs);
	FILE *f = fopen(p, "wb");
	if (f) {
		fprintf(f, "%d\n", lvl);
		fclose(f);
	}
}

void Q3E_BootEngine(void) {
	static char cmdline[4096];
	const char *extra = getenv("Q3E_ARGS");
	Sys_Print("Q3E_STAMP: ");
	Sys_Print(q3e_ios_stamp);
	Sys_Print("\n");
	// iOS-optimal engine defaults, applied INCREMENTALLY so each new default is
	// baked in exactly once. A fresh install (no config) gets con_scale plus
	// every migration level; an existing install gets only the levels above
	// its recorded marker (.q3e_migrations) — overriding a value written before
	// that default existed, without ever fighting a later user change. All are
	// +set before subsystem init, so latched cvars (s_khz, MSAA) take effect on
	// this boot. Levels:
	//   L1: s_khz 44 (engine default 22 = half rate) + 16x anisotropic
	//   L2: 4x MSAA (free on the A19 — M-016 held locked 120 at 8x under 12-bot
	//       stress; 4x is the battery-conscious default, 8x available in SETUP)
	char firstrun[512] = "";
	{
		char cfgpath[1200];
		Com_sprintf(cfgpath, sizeof(cfgpath), "%s/baseq3/q3config.cfg", q3e_docs);
		FILE *f = fopen(cfgpath, "rb");
		qboolean haveConfig = (f != NULL);
		if (f) fclose(f);
		int mlevel = haveConfig ? q3e_migration_level() : 0; // fresh = 0 -> gets all
		if (!haveConfig) {
			Q_strcat(firstrun, sizeof(firstrun), "+set con_scale 2 ");
		}
		if (mlevel < 1) {
			Q_strcat(firstrun, sizeof(firstrun),
				"+set s_khz 44 +set r_ext_texture_filter_anisotropic 16 ");
		}
		if (mlevel < 2) {
			Q_strcat(firstrun, sizeof(firstrun), "+set r_ext_multisample 4 ");
		}
	}
	char modarg[96] = "";
	if (q3e_pending_mod[0] && strcmp(q3e_pending_mod, "baseq3") != 0) {
		Com_sprintf(modarg, sizeof(modarg), "+set fs_game %s ", q3e_pending_mod);
	}
	Com_sprintf(cmdline, sizeof(cmdline),
		"+set fs_basepath %s +set fs_homepath %s +set com_skipIdLogo 1 +set r_fbo 1 "
		"+set cl_allowDownload 1 %s%s%s",
		q3e_docs, q3e_docs, firstrun, modarg, extra ? extra : "");
	Sys_Print("Q3E-SPIKE cmdline: ");
	Sys_Print(cmdline);
	Sys_Print("\n");
	if (getenv("Q3E_CONSOLE")) {
		q3e_bridge_active = qtrue;
		Q3E_ConsoleBridge_Start();
	}
	Com_Init(cmdline);
	q3e_booted = qtrue;
	if (q3e_migration_level() < Q3E_MIGRATION_LEVEL) {
		q3e_set_migration_level(Q3E_MIGRATION_LEVEL);
	}
	Sys_Print("Q3E-SPIKE Com_Init complete\n");
}

// Scene resign-active: the engine's own config flush runs one frame
// after a cvar change; a suspend-kill in that window loses settings.
// Flush synchronously here (main thread).
void Q3E_OnResignActive(void) {
	if (q3e_booted) {
		Cbuf_ExecuteText(EXEC_NOW, "writeconfig q3config.cfg\n");
		Sys_Print("Q3E-SPIKE: config flushed on resign-active\n");
	}
}

// Per-callback frame split: wall (callback-to-callback) vs engine-frame
// (inside Com_Frame, includes in-call blocking — q2repro naming lesson).
// RAM-ring buffered, one summary line per 600 frames (~5 s at 120 Hz);
// a single NSLog-equivalent every 5 s is not a measurement pollutant.

#define Q3E_FT_WINDOW 600

static uint32_t q3e_ft_busy[Q3E_FT_WINDOW];
static uint32_t q3e_ft_wall[Q3E_FT_WINDOW];
static int q3e_ft_n;
static int64_t q3e_ft_prev;

// Sim-rate: authoritative game-time advance vs wall time — the charter's
// day-one metric (the number that turns "enemies move in slow motion"
// into a diagnosis, and the exact failure mode patch 0002 fixed). 100% =
// the simulation keeps up with wall inside the display-link callback.
// Sampled only over frames where the sim is meant to advance (in-world,
// unpaused) so a legitimate menu/pause never reads as a stall.
static int      q3e_auth_prev;
static qboolean q3e_auth_have;
static double   q3e_sim_ms;       // summed authoritative advance this window (ms)
static double   q3e_sim_wall_us;  // summed wall over those same frames (us)

static int q3e_auth_clock(qboolean *active) {
	// listen server / single-player: svs.time is the monotonic cross-map
	// server clock (sv.time resets each level; svs.time does not).
	if (Cvar_VariableIntegerValue("sv_running") &&
	    !Cvar_VariableIntegerValue("cl_paused")) {
		*active = qtrue;
		return svs.time;
	}
	// pure remote client: the latest snapshot's authoritative server time.
	if (cls.state == CA_ACTIVE) {
		*active = qtrue;
		return cl.snap.serverTime;
	}
	*active = qfalse;
	return 0;
}

static int q3e_ft_cmp(const void *a, const void *b) {
	const uint32_t ua = *(const uint32_t *)a, ub = *(const uint32_t *)b;
	return (ua > ub) - (ua < ub);
}

int Q3E_ThermalState(void); // ios_metal.m (0 nominal / 1 fair / 2 serious / 3 critical)

static void q3e_ft_report(void) {
	static const char *thermal_names[] = { "nominal", "fair", "serious", "critical" };
	char line[256];
	int th = Q3E_ThermalState();
	if (th < 0 || th > 3) th = 0;
	char simstr[24];
	if (q3e_sim_wall_us > 0.0) {
		Com_sprintf(simstr, sizeof(simstr), "%.1f%%",
			(q3e_sim_ms / (q3e_sim_wall_us / 1000.0)) * 100.0);
	} else {
		Q_strncpyz(simstr, "n/a", sizeof(simstr)); // no in-world frames this window
	}
	qsort(q3e_ft_busy, Q3E_FT_WINDOW, sizeof(uint32_t), q3e_ft_cmp);
	qsort(q3e_ft_wall, Q3E_FT_WINDOW, sizeof(uint32_t), q3e_ft_cmp);
	Com_sprintf(line, sizeof(line),
		"Q3E_FT: wall p50=%.2f p95=%.2f | engine-frame p50=%.2f p95=%.2f p99=%.2f max=%.2f | sim=%s (ms, n=%d, thermal=%s)\n",
		q3e_ft_wall[Q3E_FT_WINDOW / 2] / 1000.0,
		q3e_ft_wall[(Q3E_FT_WINDOW * 95) / 100] / 1000.0,
		q3e_ft_busy[Q3E_FT_WINDOW / 2] / 1000.0,
		q3e_ft_busy[(Q3E_FT_WINDOW * 95) / 100] / 1000.0,
		q3e_ft_busy[(Q3E_FT_WINDOW * 99) / 100] / 1000.0,
		q3e_ft_busy[Q3E_FT_WINDOW - 1] / 1000.0,
		simstr, Q3E_FT_WINDOW, thermal_names[th]);
	Sys_Print(line);

	q3e_sim_ms = 0.0;
	q3e_sim_wall_us = 0.0;
}

void Q3E_Frame(void) {
	const int64_t begin = Sys_Microseconds();

	if (q3e_bridge_active) {
		Q3E_ConsoleBridge_Drain();
	}
	Q3E_Input_Frame();
	Com_Frame(qtrue); // noDelay: the CADisplayLink is the only pacer

	const int64_t end = Sys_Microseconds();
	if (q3e_ft_prev != 0) {
		const uint32_t wall_us = (uint32_t)(begin - q3e_ft_prev);
		q3e_ft_busy[q3e_ft_n] = (uint32_t)(end - begin);
		q3e_ft_wall[q3e_ft_n] = wall_us;

		// pair this frame's authoritative sim advance with its wall interval
		qboolean active;
		const int authNow = q3e_auth_clock(&active);
		if (active && q3e_auth_have) {
			const int d = authNow - q3e_auth_prev;
			if (d >= 0 && d < 1000) { // ignore level resets / source switches
				q3e_sim_ms += d;
				q3e_sim_wall_us += wall_us;
			}
		}
		q3e_auth_have = active;
		q3e_auth_prev = authNow;

		if (++q3e_ft_n == Q3E_FT_WINDOW) {
			q3e_ft_report();
			q3e_ft_n = 0;
		}
	}
	q3e_ft_prev = begin;
}

// ---- Vulkan renderer platform hooks (tr_public.h:225-228) ----

void VKimp_Init(glconfig_t *config) {
	config->vidWidth = Q3E_LayerWidth();
	config->vidHeight = Q3E_LayerHeight();
	config->windowAspect = (float)config->vidWidth / (float)config->vidHeight;
	config->colorBits = 24;
	config->depthBits = 24;
	config->stencilBits = 8;
	config->displayFrequency = Q3E_DisplayMaxFPS();
	config->isFullscreen = qtrue;
	config->deviceSupportsGamma = qfalse;
	config->driverType = GLDRV_ICD;
	config->hardwareType = GLHW_GENERIC;
	config->stereoEnabled = qfalse;
	Com_Printf("VKimp_Init(iOS): %dx%d @%dHz\n",
		config->vidWidth, config->vidHeight, config->displayFrequency);
}

void VKimp_Shutdown(qboolean unloadDLL) {
}

void *VK_GetInstanceProcAddr(VkInstance instance, const char *name) {
	return Q3E_GetInstanceProcAddr((void *)instance, name);
}

qboolean VK_CreateSurface(VkInstance instance, VkSurfaceKHR *pSurface) {
	void *surface = NULL;
	if (!Q3E_CreateMetalSurface((void *)instance, &surface)) {
		return qfalse;
	}
	*pSurface = (VkSurfaceKHR)surface;
	return qtrue;
}

// ---- gamma (no hardware ramps on iOS; r_fbo shader gamma instead) ----

void GLimp_InitGamma(glconfig_t *config) {
	config->deviceSupportsGamma = qfalse;
}

void GLimp_SetGamma(unsigned char red[256], unsigned char green[256], unsigned char blue[256]) {
}

// ---- input (spike: none — timedemo needs no input) ----

void IN_Init(void) {}
void IN_Frame(void) {}
void IN_Shutdown(void) {}
void IN_Restart(void) {}
void Sys_SendKeyEvents(void) {}
qboolean Key_CapsLockOn(void) { return qfalse; }

// ---- clipboard (paste server addresses / passwords into console + menus) ----

const char *Q3E_ClipboardText(void); // ios_metal.m (UIPasteboard)

char *Sys_GetClipboardData(void) {
	const char *s = Q3E_ClipboardText();
	size_t n;
	char *buf;
	if (!s || !s[0]) {
		return NULL;
	}
	// callers Z_Free the result (cl_keys.c/cl_ui.c) → it must be Z_Malloc'd;
	// mirror the desktop impl (first line only — strips a trailing newline).
	n = strlen(s) + 1;
	buf = Z_Malloc(n);
	Q_strncpyz(buf, s, (int)n);
	strtok(buf, "\n\r\b");
	return buf;
}
void Sys_SetClipboardBitmap(const byte *bitmap, int length) {}

// ---- sound: real AudioQueue SNDDMA lives in ios_snd.c ----

// ---- Sys_* subset normally provided by unix_main.c (excluded: its
//      main() and tty console don't apply on iOS) ----

void QDECL Sys_Error(const char *error, ...) {
	va_list argptr;
	char text[4096];

	va_start(argptr, error);
	Q_vsnprintf(text, sizeof(text), error, argptr);
	va_end(argptr);

	fprintf(stderr, "Sys_Error: %s\n", text);
	fflush(stderr);
	exit(1);
}

void NORETURN Sys_Quit(void) {
	fprintf(stderr, "Sys_Quit()\n");
	fflush(stderr);
	exit(0);
}

void Sys_Init(void) {
}

void Sys_Print(const char *msg) {
	fputs(msg, stderr);
	if (q3e_bridge_active) {
		Q3E_ConsoleBridge_Output(msg);
	}
}

void QDECL Sys_SetStatus(const char *format, ...) {
}

qboolean Sys_LowPhysicalMemory(void) {
	return qfalse;
}

const char *Sys_DefaultBasePath(void) {
	return q3e_docs;
}

char *Sys_DefaultAppPath(void) {
	return q3e_docs;
}

void Sys_Sleep(int msec) {
	if (msec > 0) {
		usleep((useconds_t)msec * 1000);
	}
}

char *Sys_ConsoleInput(void) {
	return NULL;
}

void Sys_BeginProfiling(void) {
}
